server.port: 8080

spring:
    datasource:
        url: jdbc:postgresql://dpg-ct26nsdumphs738u3de0-a.oregon-postgres.render.com:5432/biblioteca_bd_w59h
        username: biblioteca_bd_w59h_user
        password: aRxgWAY3uDXYkMBgvopMqxH5y1UdL9r8
        driver-class-name: org.postgresql.Driver
        initialize: true

    jpa: 
        hibernate:
            ddl-auto: create-drop
            generate-ddl: true

    sql:
        init:
            schema-locations: classpath:/schema-postgresql.sql
            mode: always
            platform: postgres

    
